spring:
  datasource:
    url: jdbc:postgresql://43.205.105.128:5432/postgres
    username: postgres
    password: Shivam@12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${{secrets.S3_ACCESS_KEY}}
      secret-key: ${{secrets.S3_SECRET_KEY}}
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: gift-orchids
