spring:
  application:
    name: giftOrchidsVault
  cloud:
    vault:
      kv:
        enabled: true
      authentication: TOKEN
      token: hvs.YoU9uXXxpNc4Di3W09qZ7ISg
      scheme: http
      host: 127.0.0.1
      port: 8200
  config:
    import: vault://

  datasource:
    url: jdbc:postgresql://43.205.105.128:5432/postgres
    username: postgres
    password: Shivam@12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

application:
  bucket:
    name: gift-orchids
