spring:
  datasource:
    url: jdbc:postgresql://13.235.71.28:5432/postgres
    username: postgres
    password: Shivam@12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#aws:
#  region: ap-south-1
#  s3:
#    bucket: giftorchidsbucket
#
#servlet:
#  multipart:
#    enabled: true
#    max-file-size: 5MB
#    max-request-size: 5MB
