spring:
  datasource:
    url: jdbc:postgresql://3.110.167.0:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true